version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.13.0 # <--- CHANGE THIS LINE (Note the 'v' in v2.13.0 for GHCR tags)
    container_name: mlflow-tracking-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlruns
    command: mlflow ui --host 0.0.0.0 --backend-store-uri file:///mlruns
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mlops-network

  mlops-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-housing-api-container
    ports:
      - "5001:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
    depends_on:
      mlflow-server:
        condition: service_healthy
    networks:
      - mlops-network

volumes:
  mlflow_data:

networks:
  mlops-network:
    driver: bridge