version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    container_name: mlflow-tracking-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlruns
    # --- CHANGE THIS COMMAND LINE ---
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:////mlruns/mlflow.db --default-artifact-root file:///mlruns --serve-artifacts
    networks:
      - mlops-network

  mlops-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-housing-api-container
    ports:
      - "5001:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow-server:5000
    depends_on:
      mlflow-server:
        condition: service_started
    networks:
      - mlops-network

volumes:
  mlflow_data:

networks:
  mlops-network:
    driver: bridge