name: MLOPs CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies and run tests
      run: |
        pip install -r requirements.txt
        flake8 .  # Lint
        pytest    # Test

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mlops-housing-pipeline-mlops-api:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlops-housing-pipeline-mlops-api:latest


    - name: Deploy (optional)
      if: hashFiles('deploy.sh') != ''
      run: |
        chmod +x deploy.sh
        ./deploy.sh
